import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Projects Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Projects Portfolio
        </h1>
   
        <p className={styles.description}>
          Hi, I am a web developer from San Diego, CA. <br></br>
          These are some of the projects that I've worked on.
          {' '}
        </p>

        <div className={styles.grid}>
          <a href="https://bankrollerrec.com" className={styles.card}>
            <h2>Business Card &rarr; </h2>
            <p>This is my personal website which I use to showcase my resume and some tools for stock and crypto analysis</p>
          </a>

          <a href="https://github.com/b0ndarenk07/web3" className={styles.card}>
            <h2>Projects Portfolio &rarr;</h2>
            <p>This website I developed in Node JS and Next JS</p>
          </a>

          <a
            href="https://github.com/b0ndarenk07/sys-login"
            className={styles.card}
          >
            <h2>Login System &rarr;</h2>
            <p>This is a desktop stand alone login system developed in Java and connected to cloud hosted MySQL server via Amazon Web Services.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

          <a
            href="https://fidel-cashflows.creator-spring.com/"
            className={styles.card}
          >
            <h2>Fidel Cashflows &rarr;</h2>
            <p>
              A storefront made via Teespring.
            </p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
